[package]
name = "keymap-cli"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
keymap-core = { path = "../keymap-core" }
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
env_logger = "0.11.8"
log = "0.4.29"
